//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.beryllium.xmldump.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("test.beryllium.xmldump.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,,,counters,,
        ///level,dim,region,dims,regions,chunks
        ///flat test 1,,,3,2,47
        ///,Overworld,,1,2,47
        ///,,r-1.-2.mca,0,1,5
        ///,,r0.0.mca,0,1,42
        ///,The Nether,,1,0,0
        ///,The End,,1,0,0
        ///.
        /// </summary>
        internal static string StatsProcessorTest_flatTest1_result {
            get {
                return ResourceManager.GetString("StatsProcessorTest_flatTest1_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;world&gt;
        ///  &lt;directoryInfo&gt;
        ///    &lt;fullPath&gt;C:\files\personal\proj\dev\codename-beryllium\data\SampleWorlds\flat test 1&lt;/fullPath&gt;
        ///    &lt;directory&gt;
        ///      &lt;directory name=&quot;chickenchunks&quot;&gt;
        ///        &lt;file name=&quot;loginTimes.dat&quot; /&gt;
        ///      &lt;/directory&gt;
        ///      &lt;directory name=&quot;data&quot;&gt;
        ///        &lt;directory name=&quot;redlogic-compiled-circuit-cache.dat&quot;&gt;
        ///          &lt;file name=&quot;session-counter&quot; /&gt;
        ///        &lt;/directory&gt;
        ///        &lt;file name=&quot;villages.dat&quot; /&gt;
        ///      &lt;/directory&gt;
        ///      &lt;directory name=&quot;DIM-1&quot;&gt;
        ///        &lt;direct [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlDumperTest_flatTest1_result {
            get {
                return ResourceManager.GetString("XmlDumperTest_flatTest1_result", resourceCulture);
            }
        }
    }
}
